DROP DATABASE IF EXISTS feria;
CREATE DATABASE IF NOT EXISTS feria;
USE feria;


CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    TIPO_USUARIO ENUM('organizador', 'feriante', 'expositor', 'visitante') NOT NULL
);
CREATE TABLE EVENTO (
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    LUGAR VARCHAR(255) NOT NULL,
    AFORO INT NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    ID_ORGANIZADOR INT NOT NULL,
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES USUARIO(ID_USUARIO) 
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE ESTAND (
    ID_ESTAND INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMPRESA VARCHAR(255) NOT NULL,
    CONTACTO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    ID_USUARIO INT NOT NULL, 
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE EVENTO_ESTAND (
    ID_EVENTO INT NOT NULL,
    ID_ESTAND INT NOT NULL,
    PRIMARY KEY (ID_EVENTO, ID_ESTAND),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_ESTAND) REFERENCES ESTAND(ID_ESTAND)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE ENTRADA (
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    FECHA_ENTRADA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE COMENTARIO (
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    COMENTARIO TEXT NOT NULL,
    FECHA_COMENTARIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO, FECHA_COMENTARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE NOTIFICACION (
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    MENSAJE TEXT NOT NULL,
    FECHA_ENVIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO, FECHA_ENVIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
        ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT into USUARIO(nombre, email, contraseña, tipo_usuario)
VALUES('Joel', 'joel.zotag@gmail.com', '12345aA', 'organizador');
INSERT into USUARIO(nombre, email, contraseña, tipo_usuario)
VALUES('Marina', 'marinacuello@outlook.es', '12345bB', 'feriante');
INSERT into USUARIO(nombre, email, contraseña, tipo_usuario)
VALUES('Andres', 'andres.garcia@outlook.es', '12345cC', 'expositor');
INSERT into USUARIO(nombre, email, contraseña, tipo_usuario)
VALUES('Vanesa', 'vanesarodriguez@gmail.com', '12345dD', 'visitante');

INSERT INTO ESTAND (NOMBRE_EMPRESA, CONTACTO, EMAIL, TELEFONO, UBICACION, ID_USUARIO)
VALUES ('Jorge SL', 'Jorge Lorenzano', 'jorge.lorenzano@gmail.com', '123456987', 'Fira Barcelona Angar 1', '3');

INSERT INTO EVENTO (NOMBRE, DESCRIPCION, FECHA, HORA, LUGAR, AFORO, ESTADO, UBICACION, ID_ORGANIZADOR)
VALUES ('Expo-sculture', 'exposicion de esculturas', '2025-04-24', '16:18:00', 'Fira Barcelona', '300', 'activa', 'Av. de la Reina Maria Cristina, s/n, Sants-Montjuïc', '1');

INSERT INTO feria.evento_estand (ID_EVENTO, ID_ESTAND)
VALUES ('1', '1');


